'use client';

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import type {
  AppData,
  ChatMessage,
  Conversation,
  Ingredient,
  Locale,
  MealPlan,
  PhotoAnalysis,
  Recipe,
  SearchHistoryEntry,
  ShoppingItem,
  UserProfile,
  AgentId,
} from '@/lib/types';
import { readStore, uid, writeStore, clearAllStores } from '@/lib/storage';
import { EMPTY_PROFILE, buildAiContext } from '@/lib/profileContext';
import { useI18n } from './I18nProvider';
import { useAuth } from './AuthProvider';

/**
 * Everything the user accumulates lives here and is persisted per account
 * (guests get their own bucket). Swapping localStorage for Firestore/Supabase
 * later means changing only `load` / `persist`.
 */

const EMPTY: AppData = {
  profile: EMPTY_PROFILE,
  favorites: [],
  savedRecipes: [],
  plans: [],
  analyses: [],
  conversations: [],
  shoppingList: [],
  exploredCuisines: [],
  searches: [],
};

type DataValue = {
  data: AppData;
  ready: boolean;
  /* profile */
  updateProfile: (patch: Partial<UserProfile>) => void;
  /* favorites */
  isFavorite: (recipeId: string) => boolean;
  toggleFavorite: (recipe: Recipe) => boolean;
  /* recipes generated by AI are cached so links keep working */
  cacheRecipe: (recipe: Recipe) => void;
  getCachedRecipe: (idOrSlug: string) => Recipe | undefined;
  /* plans */
  savePlan: (plan: MealPlan) => void;
  deletePlan: (id: string) => void;
  /* analyses */
  addAnalysis: (a: PhotoAnalysis) => void;
  deleteAnalysis: (id: string) => void;
  clearAnalyses: () => void;
  /* conversations */
  upsertConversation: (c: Conversation) => void;
  appendMessage: (conversationId: string, message: ChatMessage) => void;
  deleteConversation: (id: string) => void;
  clearConversations: () => void;
  conversationsFor: (agent: AgentId) => Conversation[];
  /* shopping list */
  addShoppingItems: (items: Omit<ShoppingItem, 'id' | 'addedAt' | 'checked'>[]) => number;
  addIngredients: (ingredients: Ingredient[], locale: Locale, source: string, scale?: number) => number;
  toggleShoppingItem: (id: string) => void;
  updateShoppingItem: (id: string, patch: Partial<ShoppingItem>) => void;
  removeShoppingItem: (id: string) => void;
  clearShopping: (onlyChecked?: boolean) => void;
  /* history */
  markCuisineExplored: (id: string) => void;
  addSearch: (entry: Omit<SearchHistoryEntry, 'id' | 'createdAt'>) => void;
  clearSearches: () => void;
  /* danger zone */
  exportAll: () => string;
  eraseEverything: () => void;
};

const DataContext = createContext<DataValue | null>(null);

const bucketFor = (userId?: string) => `data.${userId ?? 'guest'}`;

export function DataProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const { locale, setLocale } = useI18n();
  const [data, setData] = useState<AppData>(EMPTY);
  const [ready, setReady] = useState(false);
  const bucket = bucketFor(user?.id);
  const hydrated = useRef(false);

  // (Re)load whenever the signed-in account changes.
  useEffect(() => {
    const stored = readStore<AppData>(bucket, EMPTY);
    const merged: AppData = { ...EMPTY, ...stored, profile: { ...EMPTY_PROFILE, ...stored.profile } };
    setData(merged);
    hydrated.current = true;
    setReady(true);
    if (merged.profile.locale && merged.profile.locale !== locale) {
      setLocale(merged.profile.locale);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bucket]);

  // Persist on every change (after the initial hydration).
  useEffect(() => {
    if (!hydrated.current) return;
    writeStore(bucket, data);
  }, [bucket, data]);

  const patch = useCallback((fn: (prev: AppData) => AppData) => setData(fn), []);

  const updateProfile = useCallback(
    (p: Partial<UserProfile>) =>
      patch((prev) => {
        const profile = { ...prev.profile, ...p };
        profile.aiContext = buildAiContext(profile, profile.locale || locale);
        return { ...prev, profile };
      }),
    [patch, locale],
  );

  // Keep the generated agent context in the active language.
  useEffect(() => {
    if (!ready) return;
    setData((prev) => {
      const next = buildAiContext(prev.profile, locale);
      if (next === prev.profile.aiContext) return prev;
      return { ...prev, profile: { ...prev.profile, aiContext: next, locale } };
    });
  }, [locale, ready]);

  const isFavorite = useCallback((id: string) => data.favorites.includes(id), [data.favorites]);

  const toggleFavorite = useCallback(
    (recipe: Recipe) => {
      let added = false;
      patch((prev) => {
        const has = prev.favorites.includes(recipe.id);
        added = !has;
        return {
          ...prev,
          favorites: has
            ? prev.favorites.filter((f) => f !== recipe.id)
            : [recipe.id, ...prev.favorites],
          savedRecipes: has
            ? prev.savedRecipes.filter((r) => r.id !== recipe.id)
            : [recipe, ...prev.savedRecipes.filter((r) => r.id !== recipe.id)],
        };
      });
      return added;
    },
    [patch],
  );

  const cacheRecipe = useCallback(
    (recipe: Recipe) =>
      patch((prev) => ({
        ...prev,
        savedRecipes: [recipe, ...prev.savedRecipes.filter((r) => r.id !== recipe.id)].slice(0, 80),
      })),
    [patch],
  );

  const getCachedRecipe = useCallback(
    (idOrSlug: string) =>
      data.savedRecipes.find((r) => r.id === idOrSlug || r.slug === idOrSlug),
    [data.savedRecipes],
  );

  const savePlan = useCallback(
    (plan: MealPlan) =>
      patch((prev) => ({
        ...prev,
        plans: [plan, ...prev.plans.filter((p) => p.id !== plan.id)].slice(0, 25),
      })),
    [patch],
  );

  const deletePlan = useCallback(
    (id: string) => patch((prev) => ({ ...prev, plans: prev.plans.filter((p) => p.id !== id) })),
    [patch],
  );

  const addAnalysis = useCallback(
    (a: PhotoAnalysis) =>
      patch((prev) => ({ ...prev, analyses: [a, ...prev.analyses].slice(0, 40) })),
    [patch],
  );

  const deleteAnalysis = useCallback(
    (id: string) =>
      patch((prev) => ({ ...prev, analyses: prev.analyses.filter((a) => a.id !== id) })),
    [patch],
  );

  const clearAnalyses = useCallback(() => patch((prev) => ({ ...prev, analyses: [] })), [patch]);

  const upsertConversation = useCallback(
    (c: Conversation) =>
      patch((prev) => ({
        ...prev,
        conversations: [c, ...prev.conversations.filter((x) => x.id !== c.id)].slice(0, 40),
      })),
    [patch],
  );

  const appendMessage = useCallback(
    (conversationId: string, message: ChatMessage) =>
      patch((prev) => ({
        ...prev,
        conversations: prev.conversations.map((c) =>
          c.id === conversationId
            ? { ...c, messages: [...c.messages, message], updatedAt: Date.now() }
            : c,
        ),
      })),
    [patch],
  );

  const deleteConversation = useCallback(
    (id: string) =>
      patch((prev) => ({
        ...prev,
        conversations: prev.conversations.filter((c) => c.id !== id),
      })),
    [patch],
  );

  const clearConversations = useCallback(
    () => patch((prev) => ({ ...prev, conversations: [] })),
    [patch],
  );

  const conversationsFor = useCallback(
    (agent: AgentId) =>
      data.conversations
        .filter((c) => c.agent === agent)
        .sort((a, b) => b.updatedAt - a.updatedAt),
    [data.conversations],
  );

  /** Merges by name+unit so the same ingredient never appears twice. */
  const addShoppingItems = useCallback<DataValue['addShoppingItems']>(
    (items) => {
      let added = 0;
      patch((prev) => {
        const list = [...prev.shoppingList];
        for (const item of items) {
          const key = `${item.name.trim().toLowerCase()}|${(item.unit ?? '').toLowerCase()}`;
          const existing = list.find(
            (i) => `${i.name.trim().toLowerCase()}|${(i.unit ?? '').toLowerCase()}` === key,
          );
          if (existing) {
            if (existing.amount !== null && item.amount !== null) {
              existing.amount = Math.round((existing.amount + item.amount) * 100) / 100;
            }
          } else {
            list.push({ ...item, id: uid('item'), checked: false, addedAt: Date.now() });
            added += 1;
          }
        }
        return { ...prev, shoppingList: list };
      });
      return added;
    },
    [patch],
  );

  const addIngredients = useCallback<DataValue['addIngredients']>(
    (ingredients, loc, source, scale = 1) =>
      addShoppingItems(
        ingredients.map((ing) => ({
          name: ing.name[loc],
          amount: ing.amount === null ? null : Math.round(ing.amount * scale * 100) / 100,
          unit: ing.unit ? ing.unit[loc] : null,
          category: ing.aisle,
          source,
        })),
      ),
    [addShoppingItems],
  );

  const toggleShoppingItem = useCallback(
    (id: string) =>
      patch((prev) => ({
        ...prev,
        shoppingList: prev.shoppingList.map((i) =>
          i.id === id ? { ...i, checked: !i.checked } : i,
        ),
      })),
    [patch],
  );

  const updateShoppingItem = useCallback(
    (id: string, p: Partial<ShoppingItem>) =>
      patch((prev) => ({
        ...prev,
        shoppingList: prev.shoppingList.map((i) => (i.id === id ? { ...i, ...p } : i)),
      })),
    [patch],
  );

  const removeShoppingItem = useCallback(
    (id: string) =>
      patch((prev) => ({ ...prev, shoppingList: prev.shoppingList.filter((i) => i.id !== id) })),
    [patch],
  );

  const clearShopping = useCallback(
    (onlyChecked = false) =>
      patch((prev) => ({
        ...prev,
        shoppingList: onlyChecked ? prev.shoppingList.filter((i) => !i.checked) : [],
      })),
    [patch],
  );

  const markCuisineExplored = useCallback(
    (id: string) =>
      patch((prev) =>
        prev.exploredCuisines.includes(id)
          ? prev
          : { ...prev, exploredCuisines: [id, ...prev.exploredCuisines] },
      ),
    [patch],
  );

  const addSearch = useCallback<DataValue['addSearch']>(
    (entry) =>
      patch((prev) => ({
        ...prev,
        searches: [
          { ...entry, id: uid('q'), createdAt: Date.now() },
          ...prev.searches.filter((s) => s.query !== entry.query),
        ].slice(0, 30),
      })),
    [patch],
  );

  const clearSearches = useCallback(() => patch((prev) => ({ ...prev, searches: [] })), [patch]);

  const exportAll = useCallback(() => JSON.stringify(data, null, 2), [data]);

  const eraseEverything = useCallback(() => {
    clearAllStores();
    setData(EMPTY);
  }, []);

  const value = useMemo<DataValue>(
    () => ({
      data,
      ready,
      updateProfile,
      isFavorite,
      toggleFavorite,
      cacheRecipe,
      getCachedRecipe,
      savePlan,
      deletePlan,
      addAnalysis,
      deleteAnalysis,
      clearAnalyses,
      upsertConversation,
      appendMessage,
      deleteConversation,
      clearConversations,
      conversationsFor,
      addShoppingItems,
      addIngredients,
      toggleShoppingItem,
      updateShoppingItem,
      removeShoppingItem,
      clearShopping,
      markCuisineExplored,
      addSearch,
      clearSearches,
      exportAll,
      eraseEverything,
    }),
    [
      data,
      ready,
      updateProfile,
      isFavorite,
      toggleFavorite,
      cacheRecipe,
      getCachedRecipe,
      savePlan,
      deletePlan,
      addAnalysis,
      deleteAnalysis,
      clearAnalyses,
      upsertConversation,
      appendMessage,
      deleteConversation,
      clearConversations,
      conversationsFor,
      addShoppingItems,
      addIngredients,
      toggleShoppingItem,
      updateShoppingItem,
      removeShoppingItem,
      clearShopping,
      markCuisineExplored,
      addSearch,
      clearSearches,
      exportAll,
      eraseEverything,
    ],
  );

  return <DataContext.Provider value={value}>{children}</DataContext.Provider>;
}

export function useData(): DataValue {
  const ctx = useContext(DataContext);
  if (!ctx) throw new Error('useData must be used inside <DataProvider>');
  return ctx;
}
